// <auto-generated />
using System;
using Backend_CycleTrust.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend_CycleTrust.DAL.Migrations
{
    [DbContext(typeof(CycleTrustDbContext))]
    [Migration("20260226092125_HashPasswordSeedData")]
    partial class HashPasswordSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Bike", b =>
                {
                    b.Property<int>("BikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bike_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BikeId"));

                    b.Property<string>("BikeCondition")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("bike_condition");

                    b.Property<int?>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FrameSize")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("frame_size");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("BikeId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("bikes");

                    b.HasData(
                        new
                        {
                            BikeId = 1,
                            BikeCondition = "USED_LIKE_NEW",
                            BrandId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Xe đạp đường trường Giant Contend AR 1, khung nhôm nhẹ, groupset Shimano 105.",
                            FrameSize = "M",
                            Price = 25000000m,
                            SellerId = 3,
                            Status = "APPROVED",
                            Title = "Giant Contend AR 1 2025"
                        },
                        new
                        {
                            BikeId = 2,
                            BikeCondition = "USED_GOOD",
                            BrandId = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Xe đạp leo núi Trek Marlin 7, phuộc RockShox, 27.5 inch.",
                            FrameSize = "L",
                            Price = 18000000m,
                            SellerId = 3,
                            Status = "APPROVED",
                            Title = "Trek Marlin 7 2024"
                        },
                        new
                        {
                            BikeId = 3,
                            BikeCondition = "NEW",
                            BrandId = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Xe đạp thành phố cao cấp, khung carbon, phù hợp đi làm và tập luyện.",
                            FrameSize = "M",
                            Price = 35000000m,
                            SellerId = 3,
                            Status = "PENDING",
                            Title = "Specialized Sirrus X 4.0"
                        },
                        new
                        {
                            BikeId = 4,
                            BikeCondition = "USED_FAIR",
                            BrandId = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Xe đạp fitness nhẹ, phù hợp di chuyển hàng ngày trong thành phố.",
                            FrameSize = "S",
                            Price = 12000000m,
                            SellerId = 3,
                            Status = "APPROVED",
                            Title = "Cannondale Quick 5"
                        });
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.BikeImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("image_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<int>("BikeId")
                        .HasColumnType("integer")
                        .HasColumnName("bike_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.HasKey("ImageId");

                    b.HasIndex("BikeId");

                    b.ToTable("bike_images");
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand_name");

                    b.HasKey("BrandId");

                    b.HasIndex("BrandName")
                        .IsUnique();

                    b.ToTable("brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "Giant"
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Trek"
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "Specialized"
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Cannondale"
                        },
                        new
                        {
                            BrandId = 5,
                            BrandName = "Merida"
                        });
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_name");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Road Bike"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Mountain Bike"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "City Bike"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Folding Bike"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Electric Bike"
                        });
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.InspectionReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("report_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<int>("BikeId")
                        .HasColumnType("integer")
                        .HasColumnName("bike_id");

                    b.Property<string>("BrakeCondition")
                        .HasColumnType("text")
                        .HasColumnName("brake_condition");

                    b.Property<string>("DrivetrainCondition")
                        .HasColumnType("text")
                        .HasColumnName("drivetrain_condition");

                    b.Property<string>("FrameCondition")
                        .HasColumnType("text")
                        .HasColumnName("frame_condition");

                    b.Property<DateTime>("InspectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inspected_at");

                    b.Property<string>("InspectionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inspection_status");

                    b.Property<int>("InspectorId")
                        .HasColumnType("integer")
                        .HasColumnName("inspector_id");

                    b.Property<string>("OverallComment")
                        .HasColumnType("text")
                        .HasColumnName("overall_comment");

                    b.Property<string>("ReportFile")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("report_file");

                    b.HasKey("ReportId");

                    b.HasIndex("BikeId");

                    b.HasIndex("InspectorId");

                    b.ToTable("inspection_reports");

                    b.HasData(
                        new
                        {
                            ReportId = 1,
                            BikeId = 1,
                            BrakeCondition = "Phanh đĩa hoạt động tốt.",
                            DrivetrainCondition = "Hệ thống truyền động Shimano 105 mượt mà.",
                            FrameCondition = "Khung nhôm còn mới, không trầy xước.",
                            InspectedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InspectionStatus = "APPROVED",
                            InspectorId = 4,
                            OverallComment = "Xe trong tình trạng rất tốt, đạt tiêu chuẩn."
                        },
                        new
                        {
                            ReportId = 2,
                            BikeId = 2,
                            BrakeCondition = "Phanh cần điều chỉnh lại.",
                            DrivetrainCondition = "Xích hơi giãn, cần thay sớm.",
                            FrameCondition = "Khung nhôm có vài vết trầy nhỏ.",
                            InspectedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InspectionStatus = "APPROVED",
                            InspectorId = 4,
                            OverallComment = "Xe ổn, cần bảo dưỡng nhẹ."
                        });
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<int?>("BikeId")
                        .HasColumnType("integer")
                        .HasColumnName("bike_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_id");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("MessageId");

                    b.HasIndex("BikeId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            BikeId = 2,
                            Content = "Chào bạn, xe Trek Marlin 7 còn không ạ?",
                            ReceiverId = 3,
                            SenderId = 2,
                            SentAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MessageId = 2,
                            BikeId = 2,
                            Content = "Chào bạn, xe vẫn còn nhé. Bạn muốn xem trực tiếp không?",
                            ReceiverId = 2,
                            SenderId = 3,
                            SentAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<int>("BikeId")
                        .HasColumnType("integer")
                        .HasColumnName("bike_id");

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DepositAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("deposit_amount");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("OrderId");

                    b.HasIndex("BikeId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("SellerId");

                    b.ToTable("orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            BikeId = 1,
                            BuyerId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepositAmount = 5000000m,
                            SellerId = 3,
                            Status = "COMPLETED",
                            TotalAmount = 25000000m
                        },
                        new
                        {
                            OrderId = 2,
                            BikeId = 4,
                            BuyerId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepositAmount = 2000000m,
                            SellerId = 3,
                            Status = "PENDING",
                            TotalAmount = 12000000m
                        });
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("report_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<int?>("BikeId")
                        .HasColumnType("integer")
                        .HasColumnName("bike_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int>("ReporterId")
                        .HasColumnType("integer")
                        .HasColumnName("reporter_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("ReportId");

                    b.HasIndex("BikeId");

                    b.HasIndex("ReporterId");

                    b.ToTable("reports");

                    b.HasData(
                        new
                        {
                            ReportId = 1,
                            BikeId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Giá niêm yết không hợp lý so với tình trạng xe.",
                            ReporterId = 2,
                            Status = "PENDING"
                        });
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("review_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer")
                        .HasColumnName("buyer_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer")
                        .HasColumnName("seller_id");

                    b.HasKey("ReviewId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SellerId");

                    b.ToTable("reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            BuyerId = 2,
                            Comment = "Xe rất đẹp, đúng mô tả. Seller giao hàng nhanh!",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 1,
                            Rating = 5,
                            SellerId = 3
                        });
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "ADMIN"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "BUYER"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "SELLER"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "INSPECTOR"
                        });
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Ho Chi Minh City",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@cycletrust.com",
                            FullName = "Admin CycleTrust",
                            Password = "$2a$11$VhQo3xikBLmFMVGM3U0kYOHGlhwtAPrwjjZV4WJmkjmoqm8SuC4Pu",
                            Phone = "0901000001",
                            RoleId = 1,
                            Status = "ACTIVE"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "Ha Noi",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "buyer@cycletrust.com",
                            FullName = "Nguyen Van Buyer",
                            Password = "$2a$11$Gtt/lWpnPzDa/VVmR/fYm.rl9lzFFlpuhxY7ExHZd1huXudhQMHqm",
                            Phone = "0901000002",
                            RoleId = 2,
                            Status = "ACTIVE"
                        },
                        new
                        {
                            UserId = 3,
                            Address = "Da Nang",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "seller@cycletrust.com",
                            FullName = "Tran Thi Seller",
                            Password = "$2a$11$tBkwBXLD4x16.MkVgIvUjuuWGUQNgUhyulVRNRc8Ps2.Rb4A6Qdsm",
                            Phone = "0901000003",
                            RoleId = 3,
                            Status = "ACTIVE"
                        },
                        new
                        {
                            UserId = 4,
                            Address = "Ho Chi Minh City",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "inspector@cycletrust.com",
                            FullName = "Le Van Inspector",
                            Password = "$2a$11$QPwNKuIisbgosdAq.f.xdeEncp0Wpq4mGP2VQCkmcSyEZVg8GO/ba",
                            Phone = "0901000004",
                            RoleId = 4,
                            Status = "ACTIVE"
                        });
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Wishlist", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("wishlist_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WishlistId"));

                    b.Property<int>("BikeId")
                        .HasColumnType("integer")
                        .HasColumnName("bike_id");

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("WishlistId");

                    b.HasIndex("BikeId");

                    b.HasIndex("BuyerId", "BikeId")
                        .IsUnique();

                    b.ToTable("wishlist");

                    b.HasData(
                        new
                        {
                            WishlistId = 1,
                            BikeId = 2,
                            BuyerId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Bike", b =>
                {
                    b.HasOne("Backend_CycleTrust.DAL.Entities.Brand", "Brand")
                        .WithMany("Bikes")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend_CycleTrust.DAL.Entities.Category", "Category")
                        .WithMany("Bikes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend_CycleTrust.DAL.Entities.User", "Seller")
                        .WithMany("Bikes")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.BikeImage", b =>
                {
                    b.HasOne("Backend_CycleTrust.DAL.Entities.Bike", "Bike")
                        .WithMany("BikeImages")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.InspectionReport", b =>
                {
                    b.HasOne("Backend_CycleTrust.DAL.Entities.Bike", "Bike")
                        .WithMany("InspectionReports")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_CycleTrust.DAL.Entities.User", "Inspector")
                        .WithMany("InspectionReports")
                        .HasForeignKey("InspectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Inspector");
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Message", b =>
                {
                    b.HasOne("Backend_CycleTrust.DAL.Entities.Bike", "Bike")
                        .WithMany("Messages")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend_CycleTrust.DAL.Entities.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_CycleTrust.DAL.Entities.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Order", b =>
                {
                    b.HasOne("Backend_CycleTrust.DAL.Entities.Bike", "Bike")
                        .WithMany("Orders")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_CycleTrust.DAL.Entities.User", "Buyer")
                        .WithMany("BuyerOrders")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_CycleTrust.DAL.Entities.User", "Seller")
                        .WithMany("SellerOrders")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Buyer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Report", b =>
                {
                    b.HasOne("Backend_CycleTrust.DAL.Entities.Bike", "Bike")
                        .WithMany("Reports")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend_CycleTrust.DAL.Entities.User", "Reporter")
                        .WithMany("Reports")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Review", b =>
                {
                    b.HasOne("Backend_CycleTrust.DAL.Entities.User", "Buyer")
                        .WithMany("BuyerReviews")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_CycleTrust.DAL.Entities.Order", "Order")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_CycleTrust.DAL.Entities.User", "Seller")
                        .WithMany("SellerReviews")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Order");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.User", b =>
                {
                    b.HasOne("Backend_CycleTrust.DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Wishlist", b =>
                {
                    b.HasOne("Backend_CycleTrust.DAL.Entities.Bike", "Bike")
                        .WithMany("Wishlists")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_CycleTrust.DAL.Entities.User", "Buyer")
                        .WithMany("Wishlists")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Bike", b =>
                {
                    b.Navigation("BikeImages");

                    b.Navigation("InspectionReports");

                    b.Navigation("Messages");

                    b.Navigation("Orders");

                    b.Navigation("Reports");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Brand", b =>
                {
                    b.Navigation("Bikes");
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Category", b =>
                {
                    b.Navigation("Bikes");
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Order", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Backend_CycleTrust.DAL.Entities.User", b =>
                {
                    b.Navigation("Bikes");

                    b.Navigation("BuyerOrders");

                    b.Navigation("BuyerReviews");

                    b.Navigation("InspectionReports");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("Reports");

                    b.Navigation("SellerOrders");

                    b.Navigation("SellerReviews");

                    b.Navigation("SentMessages");

                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
